import Link from "next/link";
import {
  ArrowLeft, ArrowRight, Boxes, BrainCircuit, BriefcaseBusiness, CheckCircle2,
  ChevronDown, CircleDollarSign, ContactRound, LayoutDashboard, Megaphone,
  Package, Route, Settings2, ShieldCheck, Users, Wrench, Workflow,
} from "lucide-react";

const modules = [
  { id: "crm", name: "CRM", icon: ContactRound, description: "Keep customer relationships moving.", details: "Organize customer records, interaction history, follow-ups, CRM lists, and relationship activity in one workspace.", capabilities: ["Customer records and search", "Interaction history and follow-ups", "Relationship Pipeline and CRM lists", "CRM Focus Mode"] },
  { id: "marketing", name: "Marketing", icon: Megaphone, description: "See the performance behind your marketing.", details: "Review recorded platform analytics, audience engagement, marketing spend, and content workflows without confusing tracking with automatic publishing.", capabilities: ["Performance trends and platform metrics", "Content Pipeline", "Audience response and spend workflows", "Marketing Focus Mode"] },
  { id: "inventory", name: "Inventory", icon: Package, description: "Know what you have and what you need.", details: "Manage stock, reserved quantities, reorder thresholds, purchase orders, and incoming deliveries from one operational workspace.", capabilities: ["On-hand, reserved, and available stock", "Custom inventory fields", "Reorder Watch and purchase orders", "Deliveries and Inventory Focus Mode"] },
  { id: "dispatch", name: "Dispatch", icon: Route, description: "Coordinate jobs from assignment to completion.", details: "Track work orders, service locations, employee assignments, schedules, and progress across your active jobs.", capabilities: ["Jobs and work orders", "Assignment and scheduling", "Service locations and route readiness", "Dispatch Focus Mode"] },
  { id: "finance", name: "Finance", icon: CircleDollarSign, description: "Understand financial movement and outstanding work.", details: "Review recorded money in and out, expected payments, outstanding obligations, and finance workflows. Designed for operational visibility, not as a replacement for accounting software.", capabilities: ["Money In, Money Out, Net, and Outstanding", "Financial Flow and transaction history", "Obligations, due dates, and CSV imports", "Finance Focus Mode"] },
];

const standard = [
  { name: "Business Overview", icon: LayoutDashboard, description: "A shared starting point with operational analytics, trends, and an A.B.E. snapshot informed by your enabled modules." },
  { name: "Business Tools", icon: Wrench, description: "Team coordination, team status, and access to supported workspace tools and integrations." },
  { name: "Business FAQ", icon: Settings2, description: "Answers about the platform, its modules, Focus Mode, A.B.E., and day-to-day workflows." },
];

function DemoButton({ label = "Request a Demo" }: { label?: string }) {
  return <Link href="/business-public/explore-abe" className="inline-flex items-center justify-center gap-3 rounded-2xl border border-violet-300/50 bg-gradient-to-b from-violet-500 to-violet-800 px-7 py-4 text-sm font-black uppercase tracking-[0.08em] text-white shadow-xl transition hover:-translate-y-0.5 hover:from-violet-400 hover:to-violet-700">{label}<ArrowRight className="h-4 w-4" /></Link>;
}

export default function BusinessSalesPage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#07111F] text-white">
      <div className="pointer-events-none absolute inset-0 overflow-hidden"><div className="absolute -left-56 -top-56 h-[38rem] w-[38rem] rounded-full bg-violet-700/20 blur-3xl" /><div className="absolute -right-56 top-96 h-[42rem] w-[42rem] rounded-full bg-blue-700/15 blur-3xl" /></div>
      <div className="relative mx-auto max-w-7xl px-6 py-8 lg:px-8">
        <Link href="/business-public" className="inline-flex items-center gap-2 rounded-2xl border border-white/15 bg-white/5 px-5 py-3 text-sm font-semibold transition hover:border-violet-400/40 hover:bg-white/10"><ArrowLeft className="h-4 w-4" />Back to Business Landing Page</Link>

        <section className="mt-8 rounded-[2.5rem] border border-white/10 bg-white/[0.045] px-6 py-12 shadow-2xl backdrop-blur-xl sm:px-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-400/30 bg-violet-500/10 px-4 py-2 text-sm font-semibold text-violet-200"><BriefcaseBusiness className="h-4 w-4" /> Aether Business Pricing</div>
          <div className="mt-8 grid items-end gap-10 lg:grid-cols-[1fr_0.42fr]">
            <div><h1 className="max-w-4xl text-4xl font-black leading-[1.08] tracking-tight sm:text-6xl">One operating system. <span className="text-violet-300">Two ways to build it.</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Choose the departments your business needs today, or work directly with Team Aether to configure an operating environment for a larger, more complex organization.</p><p className="mt-4 max-w-3xl leading-7 text-slate-400">Both lanes are built around the same principle: connect visibility, operational interpretation, and the work people actually need to do.</p></div>
            <div className="rounded-[2rem] border border-violet-300/20 bg-violet-500/10 p-6"><p className="text-xs font-black uppercase tracking-[0.22em] text-violet-200">Choose your lane</p><a href="#smb" className="mt-5 flex items-center justify-between rounded-2xl border border-white/10 bg-[#07111F]/60 px-4 py-4 font-bold hover:border-violet-400/50"><span>SMB · Modular</span><span className="text-violet-200">$500 / module</span></a><a href="#enterprise" className="mt-3 flex items-center justify-between rounded-2xl border border-white/10 bg-[#07111F]/60 px-4 py-4 font-bold hover:border-violet-400/50"><span>Enterprise · Tailored</span><span className="text-violet-200">Custom quote</span></a></div>
          </div>
          <a href="#choose-lane" className="mt-9 inline-flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-white">Explore your options <ChevronDown className="h-4 w-4" /></a>
        </section>

        <section id="choose-lane" className="scroll-mt-8 py-16"><p className="text-center text-xs font-black uppercase tracking-[0.22em] text-violet-200">The right fit</p><h2 className="mt-4 text-center text-4xl font-black tracking-tight">Start with how your business operates.</h2><div className="mt-9 grid gap-5 lg:grid-cols-2">
          <a href="#smb" className="group rounded-[2rem] border border-white/10 bg-white/[0.045] p-8 transition hover:-translate-y-1 hover:border-violet-400/40"><div className="flex items-center justify-between"><span className="rounded-full border border-violet-400/30 bg-violet-500/10 px-3 py-1 text-xs font-black uppercase tracking-widest text-violet-200">SMB</span><Boxes className="h-7 w-7 text-violet-300" /></div><h3 className="mt-7 text-3xl font-black">Build Your Own Aether</h3><p className="mt-3 text-3xl font-black">$500 <span className="text-base font-semibold text-slate-400">/ module / month</span></p><p className="mt-5 leading-7 text-slate-300">Select CRM, Marketing, Inventory, Dispatch, or Finance. Add modules as you grow; keep the shared Overview and Tools workspace.</p><span className="mt-7 inline-flex items-center gap-2 font-black text-violet-200">Explore SMB <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>
          <a href="#enterprise" className="group rounded-[2rem] border border-blue-400/20 bg-blue-500/[0.055] p-8 transition hover:-translate-y-1 hover:border-blue-400/40"><div className="flex items-center justify-between"><span className="rounded-full border border-blue-300/30 bg-blue-400/10 px-3 py-1 text-xs font-black uppercase tracking-widest text-blue-200">Enterprise</span><BuildingIcon /></div><h3 className="mt-7 text-3xl font-black">Built Around Your Organization</h3><p className="mt-3 text-3xl font-black">Custom <span className="text-base font-semibold text-slate-400">monthly pricing</span></p><p className="mt-5 leading-7 text-slate-300">Team Aether evaluates headcount, operational scope, departmental requirements, and data needs to determine an appropriate configuration and quote.</p><span className="mt-7 inline-flex items-center gap-2 font-black text-blue-200">Explore Enterprise <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></a>
        </div></section>

        <section id="smb" className="scroll-mt-8 rounded-[2.5rem] border border-white/10 bg-white/[0.04] p-6 shadow-2xl sm:p-9"><span className="rounded-full border border-violet-400/30 bg-violet-500/10 px-4 py-2 text-xs font-black uppercase tracking-widest text-violet-200">Lane 01 · SMB</span><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_0.35fr]"><div><h2 className="text-4xl font-black sm:text-5xl">Your business. Your modules.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">You shouldn't have to buy an entire software stack to solve the problems in two departments. Start with the operational capabilities you need and expand your Aether environment when you're ready.</p><p className="mt-5 text-3xl font-black">$500 <span className="text-base font-semibold text-slate-400">per enabled module, per month</span></p><p className="mt-3 text-sm text-slate-400">Five operational modules available. Your total depends on the modules you select.</p></div><div className="rounded-2xl border border-white/10 bg-[#07111F]/50 p-6"><p className="text-xs font-black uppercase tracking-widest text-violet-200">How it works</p><div className="mt-5 space-y-4">{["Choose your operational modules", "Use the shared Overview and Tools workspace", "Request additions or removals as needs change"].map(item => <div key={item} className="flex gap-3 text-sm leading-6 text-slate-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-violet-300" />{item}</div>)}</div></div></div>
          <div className="mt-10 border-t border-white/10 pt-9"><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-200">Available operational modules</p><h3 className="mt-3 text-2xl font-black">Pick the departments that do the work.</h3><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{modules.map(({id,name,icon:Icon,description,details,capabilities}) => <article key={id} className="rounded-[1.75rem] border border-white/10 bg-[#07111F]/55 p-6"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-violet-400/20 bg-violet-500/10"><Icon className="h-5 w-5 text-violet-200" /></div><span className="rounded-full border border-violet-400/25 bg-violet-500/10 px-3 py-1 text-sm font-black text-violet-200">$500/mo</span></div><h4 className="mt-5 text-2xl font-black">{name}</h4><p className="mt-2 font-semibold text-violet-200">{description}</p><p className="mt-3 text-sm leading-6 text-slate-300">{details}</p><div className="mt-5 space-y-3 border-t border-white/10 pt-5">{capabilities.map(item => <div key={item} className="flex gap-2 text-sm text-slate-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />{item}</div>)}</div></article>)}</div></div>
          <div className="mt-9 rounded-[1.75rem] border border-violet-400/20 bg-violet-500/[0.07] p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-violet-200">Standard with your Business environment</p><h3 className="mt-3 text-2xl font-black">The shared foundation is included.</h3><div className="mt-6 grid gap-4 md:grid-cols-3">{standard.map(({name,icon:Icon,description}) => <div key={name} className="rounded-2xl border border-white/10 bg-[#07111F]/45 p-5"><Icon className="h-5 w-5 text-violet-200" /><h4 className="mt-3 font-black">{name}</h4><p className="mt-2 text-sm leading-6 text-slate-300">{description}</p></div>)}</div><p className="mt-5 text-sm text-slate-400">A.B.E. interprets records from your enabled modules using defined rules. It does not use generative AI or independently execute work.</p></div>
          <div className="mt-9 flex flex-col gap-5 rounded-[1.75rem] border border-violet-300/20 bg-violet-500/10 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg font-black">Start with the modules that matter.</p><p className="mt-2 text-sm text-slate-300">Talk with Team Aether about the right SMB configuration.</p></div><DemoButton label="Request an SMB Demo" /></div>
        </section>

        <section id="enterprise" className="mt-10 scroll-mt-8 rounded-[2.5rem] border border-blue-400/25 bg-blue-500/[0.055] p-6 shadow-2xl sm:p-9"><span className="rounded-full border border-blue-300/30 bg-blue-400/10 px-4 py-2 text-xs font-black uppercase tracking-widest text-blue-200">Lane 02 · Enterprise</span><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_0.35fr]"><div><h2 className="text-4xl font-black sm:text-5xl">Aether at your organization's scale.</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Larger organizations don't all have the same staffing, data volume, department structure, or coordination needs. Enterprise is scoped with Team Aether rather than priced from a one-size-fits-all list.</p><p className="mt-5 text-3xl font-black">Custom monthly quote</p><p className="mt-3 text-sm text-slate-400">Pricing is determined after reviewing your organization's requirements.</p></div><div className="rounded-2xl border border-blue-300/20 bg-[#07111F]/50 p-6"><p className="text-xs font-black uppercase tracking-widest text-blue-200">What shapes the quote</p><div className="mt-5 space-y-4">{["Team size and headcount", "Departments and workflows required", "Data needs and operational scale", "Organizational complexity and configuration"].map(item => <div key={item} className="flex gap-3 text-sm leading-6 text-slate-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-blue-300" />{item}</div>)}</div></div></div>
          <div className="mt-9 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#07111F]/45 p-6"><p className="text-xs font-black uppercase tracking-widest text-blue-200">What it solves</p><h3 className="mt-3 text-xl font-black">Complexity across departments</h3><p className="mt-4 leading-7 text-slate-300">Customer relationships, marketing, finance, inventory, and dispatch affect one another. Aether provides a shared operational environment without erasing the distinct responsibilities of each team.</p></div><div className="rounded-2xl border border-white/10 bg-[#07111F]/45 p-6"><p className="text-xs font-black uppercase tracking-widest text-blue-200">Why the pricing is custom</p><h3 className="mt-3 text-xl font-black">Fit matters more than a preset tier</h3><p className="mt-4 leading-7 text-slate-300">Team Aether works with your organization to understand its scale and requirements before determining the monthly commercial arrangement. The quote reflects the agreed scope rather than an advertised flat rate.</p></div></div>
          <div className="mt-9 border-t border-white/10 pt-9"><p className="text-xs font-black uppercase tracking-widest text-blue-200">A connected operating model</p><div className="mt-6 grid gap-4 md:grid-cols-3">{[{name:"Organizational visibility",icon:LayoutDashboard,description:"Overview and departmental analytics provide a consolidated view of the activity recorded across enabled departments."},{name:"Operational interpretation",icon:BrainCircuit,description:"A.B.E. evaluates defined conditions in real records to identify areas that may deserve attention—without generative AI."},{name:"Structured execution",icon:Workflow,description:"Department pages and Focus Mode help employees work through responsibilities while people remain in control of decisions."}].map(({name,icon:Icon,description})=><div key={name} className="rounded-2xl border border-white/10 bg-[#07111F]/45 p-5"><Icon className="h-6 w-6 text-blue-200"/><h3 className="mt-4 font-black">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{description}</p></div>)}</div></div>
          <div className="mt-9 flex flex-col gap-5 rounded-[1.75rem] border border-blue-300/20 bg-blue-400/10 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg font-black">Tell us how your organization operates.</p><p className="mt-2 text-sm text-slate-300">Request a conversation with Team Aether about Enterprise scope and pricing.</p></div><DemoButton label="Discuss Enterprise" /></div>
        </section>

        <section className="py-16 text-center"><div className="mx-auto max-w-3xl"><ShieldCheck className="mx-auto h-9 w-9 text-violet-300"/><h2 className="mt-5 text-3xl font-black sm:text-4xl">Clarity. Focus. Execution.</h2><p className="mt-5 leading-8 text-slate-300">Whether you need two departments or a broader operating environment, Aether Business is designed to help people see what's happening and coordinate what happens next.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><DemoButton /><Link href="/business-public" className="inline-flex items-center rounded-2xl border border-white/15 bg-white/5 px-7 py-4 text-sm font-black uppercase tracking-wide hover:bg-white/10">Back to Landing Page</Link></div></div></section>
      </div>
    </main>
  );
}

function BuildingIcon() { return <Users className="h-7 w-7 text-blue-300" />; }
